name = "rvy/rodeo"
version = "1.0.1"
description = "provides roblox studio's luau runtime via cli"
authors = ["rvy"]
license = "MIT"
private = true

[engines]
pesde = "^0.7.2"
lune = "^0.10.4"

[target]
environment = "lune"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
argparse = { name = "caveful_games/argparse", version = "^0.1.2", target = "lune" }
