/// Build script: scans rodeo-pkg/shims/ and rodeo-adapters/ to generate adapters_gen.rs
///
/// Convention:
///   rodeo-pkg/shims/<name>.luau              →  require("@rodeo/<name>")
///   rodeo-adapters/<alias>/src/<name>.luau    →  require("@<alias>/<name>")
///   init.luau in either                      →  require("@<alias>")  (bare alias)
///
/// @rodeo shims live in rodeo-pkg (canonical package).
/// Third-party adapters (lune, lute, etc.) live in rodeo-adapters/.

use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    // Proto compilation is in rodeo-proto crate.

    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = PathBuf::from(&out_dir).join("adapters_gen.rs");

    let mut adapters: Vec<(String, Vec<(String, PathBuf)>)> = Vec::new();

    // @rodeo: source shims from rodeo-pkg/shims/
    let rodeo_shims_dir = Path::new(&manifest_dir).join("../rodeo-pkg/shims");
    let rodeo_shims_dir = fs::canonicalize(&rodeo_shims_dir)
        .expect("rodeo-pkg/shims directory not found");
    println!("cargo:rerun-if-changed={}", rodeo_shims_dir.display());
    let shims = scan_shim_dir(&rodeo_shims_dir);
    adapters.push(("rodeo".to_string(), shims));

    // Third-party adapters: source from rodeo-adapters/*/src/
    let adapters_dir = Path::new(&manifest_dir).join("../rodeo-adapters");
    let adapters_dir = fs::canonicalize(&adapters_dir)
        .expect("rodeo-adapters directory not found");
    println!("cargo:rerun-if-changed={}", adapters_dir.display());

    let mut entries: Vec<_> = fs::read_dir(&adapters_dir)
        .expect("cannot read rodeo-adapters")
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let alias = entry.file_name().to_string_lossy().to_string();
        let src_dir = entry.path().join("src");
        if !src_dir.is_dir() {
            continue;
        }

        println!("cargo:rerun-if-changed={}", src_dir.display());
        let shims = scan_shim_dir(&src_dir);
        adapters.push((alias, shims));
    }

    // Generate Rust source
    let mut out = fs::File::create(&out_path).expect("cannot create adapters_gen.rs");

    writeln!(out, "// AUTO-GENERATED by build.rs — do not edit\n").unwrap();

    // Sanitize alias for use as Rust identifier (replace non-alphanumeric with _)
    let safe = |s: &str| -> String {
        s.chars()
            .map(|c| if c.is_alphanumeric() { c } else { '_' })
            .collect::<String>()
            .to_uppercase()
    };

    for (alias, shims) in &adapters {
        let upper = safe(alias);
        for (require_path, abs_path) in shims {
            let const_name = if require_path.is_empty() {
                format!("{}_INIT", upper)
            } else {
                format!("{}_{}", upper, safe(require_path))
            };
            // Use forward slashes for cross-platform include_str!
            let path_str = abs_path.display().to_string().replace('\\', "/");
            writeln!(out, "static {const_name}: &str = include_str!(\"{path_str}\");").unwrap();
        }
        writeln!(out).unwrap();

        writeln!(
            out,
            "static {upper}_SHIMS: [(&str, &str); {}] = [",
            shims.len()
        )
        .unwrap();
        for (require_path, _) in shims {
            let const_name = if require_path.is_empty() {
                format!("{}_INIT", upper)
            } else {
                format!("{}_{}", upper, safe(require_path))
            };
            writeln!(out, "    (\"{require_path}\", {const_name}),").unwrap();
        }
        writeln!(out, "];\n").unwrap();
    }

    writeln!(
        out,
        "static ADAPTERS: [AdapterEntry; {}] = [",
        adapters.len()
    )
    .unwrap();
    for (alias, _) in &adapters {
        let upper = safe(alias);
        writeln!(
            out,
            "    AdapterEntry {{ alias: \"@{alias}\", shims: &{upper}_SHIMS }},"
        )
        .unwrap();
    }
    writeln!(out, "];").unwrap();
}

/// Scan a directory for .luau shim files, returning (require_path, abs_path) pairs.
/// init.luau maps to "" (bare alias require), others map to their stem.
fn scan_shim_dir(dir: &Path) -> Vec<(String, PathBuf)> {
    let mut shims: Vec<(String, PathBuf)> = Vec::new();
    let mut files: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|_| panic!("cannot read {}", dir.display()))
        .filter_map(|e| e.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|ext| ext == "luau")
                .unwrap_or(false)
        })
        .collect();
    files.sort_by_key(|e| e.file_name());

    for file in files {
        let fname = file.file_name().to_string_lossy().to_string();
        let require_path = if fname == "init.luau" {
            String::new() // bare alias
        } else {
            fname.strip_suffix(".luau").unwrap().to_string()
        };
        let abs_path = fs::canonicalize(file.path()).unwrap();

        // Re-run if this shim file changes
        println!("cargo:rerun-if-changed={}", abs_path.display());

        shims.push((require_path, abs_path));
    }

    shims
}

