/// Adapter shim loader: provides pre-bundled Luau shim sources for bundle inlining.
///
/// Each adapter maps an alias (e.g. "@lune") to a set of module shims.
/// These shims replace `require("@lune/process")` etc. with IIFE-wrapped code
/// that bridges to rodeo's `_G.__rodeo_procs` runtime APIs.
///
/// The adapter registry is auto-generated by build.rs from the
/// rodeo-adapters/ directory structure. To add a new adapter:
///   1. Create rodeo-adapters/<name>/src/
///   2. Add .luau shim files (init.luau for bare alias require)
///   3. Rebuild — no Rust changes needed

pub struct AdapterEntry {
    pub alias: &'static str,
    pub shims: &'static [(&'static str, &'static str)], // (require_path, source)
}

include!(concat!(env!("OUT_DIR"), "/adapters_gen.rs"));

/// Get all registered adapters
pub fn load_adapters() -> &'static [AdapterEntry] {
    &ADAPTERS
}

/// Get the exclude patterns for darklua bundling (e.g. "@lune/**")
pub fn exclude_patterns() -> Vec<String> {
    let mut patterns = Vec::new();
    for a in &ADAPTERS {
        patterns.push(a.alias.to_string()); // bare: @rodeo
        patterns.push(format!("{}/**", a.alias)); // sub-modules: @rodeo/**
    }
    patterns
}
